name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
    $CHANGES
category-template: '### $TITLE'
change-template: '- $TITLE #$NUMBER @$AUTHOR'
change-title-escapes: '\<*_&'
no-changes-template: 'No changes'
categories:
    - title: '⚠️ Needs Changelog Edit'
      label: 'needs-changelog-edit'
    - title: 'Breaking Changes'
      label: 'breaking'
    - title: 'Features'
      label: 'feature'
    - title: 'Bug Fixes'
      label: 'bugfix'
    - title: 'Other'
      label: 'other'
exclude-labels:
    - 'skip-changelog'
version-resolver:
    major:
        labels:
            - 'breaking'
    minor:
        labels:
            - 'feature'
    patch:
        labels:
            - 'bugfix'
            - 'other'
    default: 'patch'
autolabeler:
    - label: 'feature'
      branch:
          - '/feature/i'
      title:
          - '/feature/i'
    - label: 'bugfix'
      branch:
          - '/fix/i'
      title:
          - '/fix/i'
    - label: 'other'
      branch:
          - '/^other/i'
    - label: 'breaking'
      branch:
          - '/^breaking-/i'
