name: npm Publish

on:
    release:
        types: [published]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 16
                  cache: yarn
            - run: yarn install --frozen-lockfile
            - run: yarn lint
            - run: yarn test

    publish-gpr:
        needs: test
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 16
                  cache: yarn
            - run: yarn install --frozen-lockfile
            - run: yarn build
            - uses: JS-DevTools/npm-publish@v1
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  registry: https://npm.pkg.github.com
